### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by KarellenX** [Razzeee/metadata.tvdb.com.python#2]
I noticed that the log is spammed with the following...

`XML
CAddonSettings[metadata.tvdb.com.python]: trying to load setting definitions from old format...`

I was under the impression this would not happen in v19. It does make the log more difficult to read trying to ignore and skip past those lines while diagnosing scraping issues for members.

That message is part of a 5 line message. It was repeated **983 times** In the five shows I scraped which equates to an additional **4,915 lines of spam**
(hopefully that can give you some indication why I have been so frustrated with that issue in v18 which nobody wanted to fix in the other scrapers. It is not unusual to have thousands of lines.) :)

**Comment by Razzeee** [comment]
This one should be fixed with the latest update

**Comment by KarellenX** [comment]
Tested the latest update. Still contains lots of settings errors / cannot find / fallback messages...

```XML
DEBUG: CurlFile::Open(0x1ca8eba3f20) http://thetvdb.com/banners/graphical/253573-g3.jpg
DEBUG: CAddonSettings[metadata.tvdb.com.python]: loading setting definitions
DEBUG: CAddonSettings[metadata.tvdb.com.python]: loading setting values
DEBUG: CSettingsManager: requested setting (fallback) was not found.
DEBUG: CAddonSettings[metadata.tvdb.com.python]: failed to find definition for setting fallback. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (fanart) was not found.
DEBUG: CAddonSettings[metadata.tvdb.com.python]: failed to find definition for setting fanart. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (token) was not found.
DEBUG: CAddonSettings[metadata.tvdb.com.python]: failed to find definition for setting token. Creating a setting on-the-fly...
DEBUG: metadata.tvdb.com.python: Called addon with params: ['plugin://metadata.tvdb.com.python/', '4', '?action=getepisodedetails&url=7146210', 'resume:false']```

Fanart has been scraped, though.

I think that might be the fanart issue you mentioned earlier.

**Comment by Razzeee** [comment]
I'm no sure where this is coming from, we can probably still get rid of the token one, but the other ones are weird.

**Comment by Razzeee** [comment]
Seems to be gone for me, but I also removed these from the user settings in my user folder.
